package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.Exercise;
import com.fois.Back_end_fois_smile.entity.ExerciseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExerciseMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.exercise
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    long countByExample(ExerciseExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.exercise
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    int deleteByExample(ExerciseExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.exercise
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    int deleteByPrimaryKey(String mabt);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.exercise
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    int insert(Exercise record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.exercise
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    int insertSelective(Exercise record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.exercise
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    List<Exercise> selectByExample(ExerciseExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.exercise
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    Exercise selectByPrimaryKey(String mabt);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.exercise
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Exercise record, @Param("example") ExerciseExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.exercise
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    int updateByExample(@Param("record") Exercise record, @Param("example") ExerciseExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.exercise
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    int updateByPrimaryKeySelective(Exercise record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.exercise
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    int updateByPrimaryKey(Exercise record);
}