package com.fois.Back_end_fois_smile.entity;

public class Alphabet {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.alphabet.mabang
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    private String mabang;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.alphabet.tenbang
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    private String tenbang;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.alphabet.mabang
     * @return  the value of schema01.alphabet.mabang
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    public String getMabang() {
        return mabang;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.alphabet.mabang
     * @param mabang  the value for schema01.alphabet.mabang
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    public void setMabang(String mabang) {
        this.mabang = mabang;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.alphabet.tenbang
     * @return  the value of schema01.alphabet.tenbang
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    public String getTenbang() {
        return tenbang;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.alphabet.tenbang
     * @param tenbang  the value for schema01.alphabet.tenbang
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    public void setTenbang(String tenbang) {
        this.tenbang = tenbang;
    }
}