package com.fois.Back_end_fois_smile.entity;

public class Exercise {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.exercise.mabt
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    private String mabt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.exercise.tenbt
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    private String tenbt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.exercise.mabh
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    private String mabh;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.exercise.mabt
     * @return  the value of schema01.exercise.mabt
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public String getMabt() {
        return mabt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.exercise.mabt
     * @param mabt  the value for schema01.exercise.mabt
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public void setMabt(String mabt) {
        this.mabt = mabt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.exercise.tenbt
     * @return  the value of schema01.exercise.tenbt
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public String getTenbt() {
        return tenbt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.exercise.tenbt
     * @param tenbt  the value for schema01.exercise.tenbt
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public void setTenbt(String tenbt) {
        this.tenbt = tenbt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.exercise.mabh
     * @return  the value of schema01.exercise.mabh
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public String getMabh() {
        return mabh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.exercise.mabh
     * @param mabh  the value for schema01.exercise.mabh
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public void setMabh(String mabh) {
        this.mabh = mabh;
    }
}