package com.fois.Back_end_fois_smile.entity;

public class Kaiwa {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kaiwa.maht
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    private String maht;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kaiwa.tenht
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    private String tenht;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kaiwa.maht
     * @return  the value of schema01.kaiwa.maht
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    public String getMaht() {
        return maht;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kaiwa.maht
     * @param maht  the value for schema01.kaiwa.maht
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    public void setMaht(String maht) {
        this.maht = maht;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kaiwa.tenht
     * @return  the value of schema01.kaiwa.tenht
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    public String getTenht() {
        return tenht;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kaiwa.tenht
     * @param tenht  the value for schema01.kaiwa.tenht
     * @mbg.generated  Thu Jun 10 20:38:09 ICT 2021
     */
    public void setTenht(String tenht) {
        this.tenht = tenht;
    }
}