package com.fois.Back_end_fois_smile.entity;

import java.util.Date;

public class TestTranscript {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.test_transcript.mabd
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    private Integer mabd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.test_transcript.diem
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    private Float diem;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.test_transcript.matk
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    private Integer matk;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.test_transcript.mabaikt
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    private String mabaikt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.test_transcript.thoigian
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    private Date thoigian;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.test_transcript.mabd
     * @return  the value of schema01.test_transcript.mabd
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public Integer getMabd() {
        return mabd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.test_transcript.mabd
     * @param mabd  the value for schema01.test_transcript.mabd
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public void setMabd(Integer mabd) {
        this.mabd = mabd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.test_transcript.diem
     * @return  the value of schema01.test_transcript.diem
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public Float getDiem() {
        return diem;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.test_transcript.diem
     * @param diem  the value for schema01.test_transcript.diem
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public void setDiem(Float diem) {
        this.diem = diem;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.test_transcript.matk
     * @return  the value of schema01.test_transcript.matk
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public Integer getMatk() {
        return matk;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.test_transcript.matk
     * @param matk  the value for schema01.test_transcript.matk
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public void setMatk(Integer matk) {
        this.matk = matk;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.test_transcript.mabaikt
     * @return  the value of schema01.test_transcript.mabaikt
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public String getMabaikt() {
        return mabaikt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.test_transcript.mabaikt
     * @param mabaikt  the value for schema01.test_transcript.mabaikt
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public void setMabaikt(String mabaikt) {
        this.mabaikt = mabaikt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.test_transcript.thoigian
     * @return  the value of schema01.test_transcript.thoigian
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public Date getThoigian() {
        return thoigian;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.test_transcript.thoigian
     * @param thoigian  the value for schema01.test_transcript.thoigian
     * @mbg.generated  Sat Jun 12 16:57:50 ICT 2021
     */
    public void setThoigian(Date thoigian) {
        this.thoigian = thoigian;
    }
}